import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "../Components/layout/Header";
import AppProvider from '../Components/AppContext';

const roboto = Roboto({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ['400','500','700']
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased`}
      >
        <main className="max-w-4xl mx-auto border p-4">
        <AppProvider>
        <Header/>
        {children}
        <footer className="border-t p-8 text-center text-gray-500 mt-16">
        &copy; 2023 All rights reserved
      </footer>
      </AppProvider>
        </main>
        
      </body>
    </html>
  );
}
